// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv69l7qpHQdRmltOsyroN1LqLvxxzHiBA',
    appId: '1:485774833575:web:8bfe96d0dd13356f3da882',
    messagingSenderId: '485774833575',
    projectId: 'projectlab-9bb51',
    authDomain: 'projectlab-9bb51.firebaseapp.com',
    storageBucket: 'projectlab-9bb51.firebasestorage.app',
    measurementId: 'G-VXM0YM95PL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT3KMNjh99SJyW51TPChhHUmaMJJxik9U',
    appId: '1:485774833575:android:0d5cb9c8408ef1283da882',
    messagingSenderId: '485774833575',
    projectId: 'projectlab-9bb51',
    storageBucket: 'projectlab-9bb51.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoYnWKpCeaNXfFtqVb8G1T-f8Sm2RUbgQ',
    appId: '1:485774833575:ios:53b66d670ccb95453da882',
    messagingSenderId: '485774833575',
    projectId: 'projectlab-9bb51',
    storageBucket: 'projectlab-9bb51.firebasestorage.app',
    iosBundleId: 'com.dino.project.lab.projectLab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoYnWKpCeaNXfFtqVb8G1T-f8Sm2RUbgQ',
    appId: '1:485774833575:ios:53b66d670ccb95453da882',
    messagingSenderId: '485774833575',
    projectId: 'projectlab-9bb51',
    storageBucket: 'projectlab-9bb51.firebasestorage.app',
    iosBundleId: 'com.dino.project.lab.projectLab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAv69l7qpHQdRmltOsyroN1LqLvxxzHiBA',
    appId: '1:485774833575:web:c0358e2ca247b0173da882',
    messagingSenderId: '485774833575',
    projectId: 'projectlab-9bb51',
    authDomain: 'projectlab-9bb51.firebaseapp.com',
    storageBucket: 'projectlab-9bb51.firebasestorage.app',
    measurementId: 'G-5R25LKS06J',
  );
}
